#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 449575-web-01 18.206.197.195:80 check
        server 449575-web-02 52.91.147.237:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
